---

- name: Installing and launching Metricbeat on webservers
  hosts: webservers
  become: true
  tasks:

  #Download and Install Metricbeat7.4.0 deb file using dpkg
  - name: download metricbeat deb
    command: curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  #Copy config file to webservers
  - name: Copy metricbeat configuration file
    copy:
      src: /etc/ansible/roles/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  #Enable and Configure Docker Module
  - name: Enable and Configure Docker
    command: sudo metricbeat modules enable docker

  #Setup metricbeat
  - name: setup metricbeat
    command: sudo metricbeat setup

  #Start metricbeat
  - name: start metricbeat service
    command: sudo service metricbeat start